[[main]]
name = "About"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog/"
weight = 3
hasChildren = true

[[main]]
name = "Affinity"
url = "/class/affinity/"
weight = 1
parent = "Class"

[[main]]
name = "AI & Tech"
url = "/blog/ai-tech/"
weight = 1
parent = "Blog"

[[main]]
name = "성경연구"
url = "/blog/bible-study/"
weight = 2
parent = "Blog"

[[main]]
name = "세컨드브레인"
url = "/blog/second-brain/"
weight = 3
parent = "Blog"

[[main]]
name = "주간 AI 트렌드"
url = "/blog/weekly-ai-trends/"
weight = 4
parent = "Blog"

[[main]]
name = "프리젠테이션"
url = "/blog/presentation/"
weight = 5
parent = "Blog"

[[main]]
name = "특이점"
url = "/blog/singularity/"
weight = 6
parent = "Blog"

[[main]]
name = "홈페이지 만들기"
url = "/blog/ssg/"
weight = 7
parent = "Blog"

[[main]]
name = "컨퍼런스 리뷰"
url = "/blog/conference-review/"
weight = 8
parent = "Blog"

[[main]]
name = "Class"
url = "/class/"
weight = 4
hasChildren = true

[[main]]
name = "AI 공부법"
url = "/class/ai-study-guide/"
weight = 2
parent = "Class"

[[main]]
name = "Notebook LM"
url = "/class/notebook-lm/"
weight = 3
parent = "Class"

[[main]]
name = "Gemini Gems"
url = "/class/gemini-gems/"
weight = 4
parent = "Class"

[[main]]
name = "Gemini Canvas"
url = "/class/gemini-canvas/"
weight = 5
parent = "Class"

[[main]]
name = "Databank"
url = "/databank/"
weight = 5
hasChildren = true

[[main]]
name = "이슬비전도카드"
url = "/databank/rain-card/"
weight = 1
parent = "Databank"

[[main]]
name = "성경자료실"
url = "/databank/bible-resources/"
weight = 2
parent = "Databank"

[[main]]
name = "노션 템플릿"
url = "/databank/notion-templates/"
weight = 3
parent = "Databank"

[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "/"
weight = 2

[[footer]]
name = "Blog"
url = "/blog/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 4
